name = "bouncesolver"
version = "0.1.0"
license = "license"
author = "Thomas"
maintainer = "thomas.biekoetter@desy.de"
copyright = "Copyright 2026, Thomas"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
gradmin = { git = "https://gitlab.com/thomas.biekoetter/gradmin.git", profile = "release" }
odeint = { git = "https://gitlab.com/thomas.biekoetter/odeint.git" }
linalg = { git = "https://gitlab.com/thomas.biekoetter/fpm-linalg.git" }
cubicsplines = { git = "https://github.com/thomasbiekoetter/cubicsplines" }
bspline-fortran = { git="https://github.com/jacobwilliams/bspline-fortran.git" }
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }
openmp="*"
[[executable]]
name = "pdm_thickwalled"
source-dir = "app"
main = "pdm_thickwalled.f90"
[[test]]
name = "pdm_thickwalled"
source-dir = "test"
main = "pdm_thickwalled.f90"
[[test]]
name = "pdm_thickwalledstraight"
source-dir = "test"
main = "pdm_thickwalledstraight.f90"
[[test]]
name = "cxsm"
source-dir = "test"
main = "cxsm.f90"
[executable.dependencies]
cxsm = { git="git@gitlab.com:gws-in-the-cxsm/cxsm.git", profile="release" }
[features]
debug.flags = "-fPIC -O0 -g "
debug.gfortran.flags = "-fbounds-check -fbacktrace -Wall -Wuninitialized -fmax-errors=1 -fcheck=all -ffpe-trap=invalid,zero,overflow"
debug.ifx.flags = "-check bounds -check pointer -traceback"
release.flags = "-O3"
release.gfortran.flags = "-march=native -fmax-errors=1 -ffixed-line-length-none -fno-range-check"
release.ifx.flags = "-xHost -march"
[profiles]
debug = ["debug"]
release = ["release"]
