name = "bouncesolver"
version = "0.1.0"
license = "license"
author = "Thomas"
maintainer = "thomas.biekoetter@desy.de"
copyright = "Copyright 2026, Thomas"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
test = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
# gradmin = { git = "git@gitlab.com:thomas.biekoetter/gradmin.git" }
gradmin = { path = "../gradmin" }
odeint = { git = "git@gitlab.com:thomas.biekoetter/odeint.git" }
evortran = { git = "https://gitlab.com/thomas.biekoetter/evortran.git" }
linalg = { git = "https://gitlab.com/thomas.biekoetter/fpm-linalg.git" }
cubicsplines = { git = "https://github.com/thomasbiekoetter/cubicsplines" }
bspline-fortran = { git="https://github.com/jacobwilliams/bspline-fortran.git" }
openmp="*"
[dev-dependencies]
csv-fortran = { git="https://github.com/jacobwilliams/csv-fortran.git" }
[[executable]]
name = "pdm_thickwalled"
source-dir = "app"
main = "pdm_thickwalled.f90"
[[test]]
name = "pdm_thickwalled"
source-dir = "test"
main = "pdm_thickwalled.f90"
